import Navbar from "@/Componunst/Navbar/Navbar";
import"./globals.css";

export const metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
       <Navbar/>
        <main className="main">
          <section className="main-sec">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
